"""API schemas package."""

from .composition import (
    AudioConfig,
    BulkCancelResponse,
    ClipConfig,
    CompositionCancelResponse,
    CompositionCreateRequest,
    CompositionListResponse,
    CompositionMetadataResponse,
    CompositionResponse,
    CompositionStatusResponse,
    DownloadResponse,
    InputFileInfo,
    OutputFileInfo,
    OutputSettings,
    OverlayConfig,
    ProcessingStage,
    ProcessingStageInfo,
    ResourceMetrics,
)
from .errors import ErrorDetail, ErrorResponse
from .folder import (
    BreadcrumbItem,
    FolderContentsResponse,
    FolderCreateRequest,
    FolderDeleteResponse,
    FolderListResponse,
    FolderResponse,
    FolderTreeNode,
    FolderUpdateRequest,
)
from .project import (
    BulkOperationRequest,
    BulkOperationResponse,
    ConflictDetectionResponse,
    ConflictResolutionRequest,
    ProjectCreateRequest,
    ProjectDetailResponse,
    ProjectDuplicateRequest,
    ProjectListResponse,
    ProjectResponse,
    ProjectShareRequest,
    ProjectShareResponse,
    ProjectShareUpdateRequest,
    ProjectUpdateRequest,
    ProjectVersionDetailResponse,
    ProjectVersionListResponse,
    ProjectVersionResponse,
    SharePermissionEnum,
    SortBy,
    SortOrder,
    VersionDiffResponse,
)
from .job import JobCancelResponse, JobListResponse, JobResponse, JobStatus
from .media import (
    MediaAssetListResponse,
    MediaAssetResponse,
    MediaStatus,
    MediaType,
    MediaUploadRequest,
    MediaUploadResponse,
)
from .replicate import (
    NanoBananaErrorResponse,
    NanoBananaRequest,
    NanoBananaResponse,
)
from .tag import (
    BulkTagRequest,
    BulkTagResponse,
    TagCreateRequest,
    TagDeleteResponse,
    TagListResponse,
    TagOperationMode,
    TagResponse,
    TagSuggestion,
    TagSuggestResponse,
    TagUpdateRequest,
)
from .websocket import (
    ConnectionState,
    MediaEventType,
    WSBaseMessage,
    WSClientMessage,
    WSConnectedMessage,
    WSErrorMessage,
    WSFolderCreatedMessage,
    WSFolderDeletedMessage,
    WSFolderUpdatedMessage,
    WSHeartbeatMessage,
    WSMediaBaseMessage,
    WSMediaConnectedMessage,
    WSMediaDeletedMessage,
    WSMediaThumbnailReadyMessage,
    WSMediaUpdatedMessage,
    WSMediaUploadedMessage,
    WSMessageType,
    WSPongMessage,
    WSProgressMessage,
    WSStatusMessage,
)

__all__ = [
    # Composition schemas
    "ClipConfig",
    "AudioConfig",
    "OverlayConfig",
    "OutputSettings",
    "CompositionCreateRequest",
    "CompositionResponse",
    "CompositionListResponse",
    "CompositionStatusResponse",
    "CompositionMetadataResponse",
    "CompositionCancelResponse",
    "BulkCancelResponse",
    "DownloadResponse",
    "ProcessingStage",
    "ProcessingStageInfo",
    "ResourceMetrics",
    "InputFileInfo",
    "OutputFileInfo",
    # Error schemas
    "ErrorResponse",
    "ErrorDetail",
    # Folder schemas
    "FolderCreateRequest",
    "FolderUpdateRequest",
    "FolderResponse",
    "FolderTreeNode",
    "FolderListResponse",
    "FolderContentsResponse",
    "FolderDeleteResponse",
    "BreadcrumbItem",
    # Project schemas
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectResponse",
    "ProjectDetailResponse",
    "ProjectListResponse",
    "ProjectShareRequest",
    "ProjectShareUpdateRequest",
    "ProjectShareResponse",
    "ProjectVersionResponse",
    "ProjectVersionDetailResponse",
    "ProjectVersionListResponse",
    "VersionDiffResponse",
    "ConflictDetectionResponse",
    "ConflictResolutionRequest",
    "ProjectDuplicateRequest",
    "BulkOperationRequest",
    "BulkOperationResponse",
    "SharePermissionEnum",
    "SortBy",
    "SortOrder",
    # Job schemas
    "JobStatus",
    "JobResponse",
    "JobListResponse",
    "JobCancelResponse",
    # Media schemas
    "MediaType",
    "MediaStatus",
    "MediaUploadRequest",
    "MediaUploadResponse",
    "MediaAssetResponse",
    "MediaAssetListResponse",
    # Replicate schemas
    "NanoBananaRequest",
    "NanoBananaResponse",
    "NanoBananaErrorResponse",
    # Tag schemas
    "TagOperationMode",
    "TagCreateRequest",
    "TagUpdateRequest",
    "TagResponse",
    "TagListResponse",
    "TagSuggestion",
    "TagSuggestResponse",
    "BulkTagRequest",
    "BulkTagResponse",
    "TagDeleteResponse",
    # WebSocket schemas
    "WSMessageType",
    "WSBaseMessage",
    "WSProgressMessage",
    "WSStatusMessage",
    "WSErrorMessage",
    "WSHeartbeatMessage",
    "WSPongMessage",
    "WSConnectedMessage",
    "ConnectionState",
    "WSClientMessage",
    # Media WebSocket schemas
    "MediaEventType",
    "WSMediaBaseMessage",
    "WSMediaUploadedMessage",
    "WSMediaUpdatedMessage",
    "WSMediaDeletedMessage",
    "WSMediaThumbnailReadyMessage",
    "WSFolderCreatedMessage",
    "WSFolderUpdatedMessage",
    "WSFolderDeletedMessage",
    "WSMediaConnectedMessage",
]
